name: Deploy Storefront

on:
  push:
    branches: [main, staging]
    paths:
      - 'storefront/**'
      - '.github/workflows/deploy-storefront.yml'
      - 'deploy-storefront-trigger'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy-storefront:
    name: Deploy Storefront
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'production' || 'staging') }}
    
    env:
      NODE_ENV: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'production' || 'staging') }}
      GITHUB_ACTIONS: "true"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.4.0 --activate
      
      - name: Install dependencies
        working-directory: storefront
        run: yarn install
      
      - name: Run tests
        working-directory: storefront
        run: yarn test || echo "No tests found, continuing..."
      
      - name: Build application
        working-directory: storefront
        run: yarn build
      
      - name: Generate environment file
        run: |
          cat > storefront/.env.${{ env.NODE_ENV }} << EOL
          NEXT_PUBLIC_MEDUSA_BACKEND_URL=${{ secrets.STOREFRONT_NEXT_PUBLIC_MEDUSA_BACKEND_URL }}
          NEXT_PUBLIC_BASE_URL=${{ secrets.STOREFRONT_NEXT_PUBLIC_BASE_URL }}
          REVALIDATE_SECRET=${{ secrets.STOREFRONT_REVALIDATE_SECRET }}
          EOL
          # Copy to temp location for deployment
          mkdir -p /tmp
          cp storefront/.env.${{ env.NODE_ENV }} /tmp/storefront.env
      
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add host key to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_HOST_KEY }}" >> ~/.ssh/known_hosts
      
      - name: Deploy to ${{ env.NODE_ENV }}
        run: |
          chmod +x ./scripts/deploy-storefront.sh
          set -e  # Exit immediately if a command fails
          echo "Deploying to ${{ env.NODE_ENV }} environment using IP ${{ secrets[format('STOREFRONT_{0}_IP', env.NODE_ENV == 'production' && 'PROD' || 'STAGING')] }}"
          ./scripts/deploy-storefront.sh ${{ env.NODE_ENV }} ${{ secrets[format('STOREFRONT_{0}_IP', env.NODE_ENV == 'production' && 'PROD' || 'STAGING')] }}
      
      - name: Verify deployment
        if: success()
        run: |
          echo "Storefront successfully deployed to ${{ env.NODE_ENV }} environment!" 