name: Deploy to Production

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
          
      - name: Configure AWS Credentials for Terraform backend
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.SPACES_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SPACES_SECRET_KEY }}
          aws-region: us-west-1  # Required but not used for DO Spaces
          
      - name: Terraform Init
        working-directory: ./terraform
        env:
          TF_VAR_do_token: ${{ secrets.DO_API_TOKEN }}
        run: terraform init
        
      - name: Terraform Apply
        working-directory: ./terraform
        env:
          TF_VAR_do_token: ${{ secrets.DO_API_TOKEN }}
          TF_VAR_environment: production
          TF_VAR_admin_email: ${{ secrets.ADMIN_EMAIL }}
          TF_VAR_admin_password: ${{ secrets.ADMIN_PASSWORD }}
          TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
          TF_VAR_cookie_secret: ${{ secrets.COOKIE_SECRET }}
          TF_VAR_revalidate_secret: ${{ secrets.REVALIDATE_SECRET }}
          TF_VAR_resend_api_key: ${{ secrets.RESEND_API_KEY }}
          TF_VAR_spaces_access_key: ${{ secrets.SPACES_ACCESS_KEY }}
          TF_VAR_spaces_secret_key: ${{ secrets.SPACES_SECRET_KEY }}
          TF_VAR_ssh_private_key_path: /tmp/ssh_key
        run: |
          # Save SSH key
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          
          # Apply Terraform changes
          terraform apply -auto-approve
          
      - name: Setup environment and deploy application
        working-directory: ./scripts
        run: |
          # Make scripts executable
          chmod +x deploy.sh setup-env.sh deploy-backend.sh deploy-storefront.sh
          
          # Get server IPs from Terraform
          cd ../terraform
          BACKEND_IP=$(terraform output -json backend_ip | jq -r '.')
          STOREFRONT_IP=$(terraform output -json storefront_ip | jq -r '.')
          cd ../scripts
          
          # Setup environment variables on servers
          ./setup-env.sh production $BACKEND_IP $STOREFRONT_IP
          
          # Deploy the application
          ./deploy.sh production $BACKEND_IP $STOREFRONT_IP 