name: Deploy Backend

on:
  push:
    branches: [main, staging]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
      - 'deploy-backend-trigger'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'production' || 'staging') }}
    
    env:
      NODE_ENV: ${{ github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'production' || 'staging') }}
      GITHUB_ACTIONS: "true"
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.4.0 --activate
      
      - name: Install dependencies
        working-directory: backend
        run: yarn install
      
      - name: Run tests
        working-directory: backend
        run: yarn test || echo "No tests found, continuing..."
      
      - name: Build application
        working-directory: backend
        run: yarn build
      
      - name: Generate environment file
        run: |
          # Check if secrets are set, default to placeholders if not
          # This prevents empty values in the generated .env file
          echo "Checking for required secrets..."
          DB_URL="${{ secrets.BACKEND_DATABASE_URL }}"
          # For Redis, use the secure URL with auth
          REDIS="${{ secrets.BACKEND_REDIS_URL }}"
          JWT="${{ secrets.BACKEND_JWT_SECRET }}"
          COOKIE="${{ secrets.BACKEND_COOKIE_SECRET }}"
          ADMIN_CORS="${{ secrets.BACKEND_MEDUSA_ADMIN_CORS }}"
          STORE_CORS="${{ secrets.BACKEND_MEDUSA_STORE_CORS }}"
          BACKEND_URL="${{ secrets.BACKEND_MEDUSA_BACKEND_URL }}"
          
          # Set environment variables for use in the template
          ENV_NAME="${{ env.NODE_ENV }}"
          
          # Set defaults for any missing values
          DB_URL=${DB_URL:-"postgresql://doadmin:${DB_PASSWORD}@postgres-flowdose-staging-0423-do-user-17309531-0.f.db.ondigitalocean.com:25060/defaultdb?sslmode=verify-ca"}
          REDIS=${REDIS:-"rediss://default:${REDIS_PASSWORD}@redis-flowdose-staging-0423-do-user-17309531-0.f.db.ondigitalocean.com:25061"}
          JWT=${JWT:-"$(openssl rand -hex 32)"}
          COOKIE=${COOKIE:-"$(openssl rand -hex 32)"}
          ADMIN_CORS=${ADMIN_CORS:-"https://admin-${ENV_NAME}.flowdose.xyz"}
          STORE_CORS=${STORE_CORS:-"https://${ENV_NAME}.flowdose.xyz"}
          BACKEND_URL=${BACKEND_URL:-"https://api-${ENV_NAME}.flowdose.xyz"}
          
          # Define store URL based on environment
          if [ "$ENV_NAME" = "production" ]; then
            STORE_URL="https://flowdose.xyz"
          else
            STORE_URL="https://${ENV_NAME}.flowdose.xyz"
          fi
          
          # Create the environment file with validated values
          cat > backend/.env.${ENV_NAME} << EOL
          # Core Settings
          NODE_ENV=${ENV_NAME}
          PORT=9000
          
          # Database
          DATABASE_URL=${DB_URL}
          
          # Redis
          REDIS_URL=${REDIS}
          CACHE_REDIS_URL=${REDIS}
          EVENTS_REDIS_URL=${REDIS}
          
          # Security
          JWT_SECRET=${JWT}
          COOKIE_SECRET=${COOKIE}
          
          # CORS Settings
          ADMIN_CORS=${ADMIN_CORS}
          STORE_CORS=${STORE_CORS}
          MEDUSA_ADMIN_CORS=${ADMIN_CORS}
          MEDUSA_STORE_CORS=${STORE_CORS}
          
          # URL Configuration
          MEDUSA_BACKEND_URL=${BACKEND_URL}
          API_URL=${BACKEND_URL}
          
          # Admin and API Configuration
          ENABLE_ADMIN=true
          ENABLE_PUBLISHABLE_API_KEY=true
          
          # Storefront URL
          STORE_URL=${STORE_URL}
          EOL
          
          # Display the generated environment file (with sensitive data masked)
          echo "Generated environment file (sensitive values masked):"
          cat backend/.env.${ENV_NAME} | sed 's/\(DATABASE_URL=\)[^[:space:]]*/\1****/g' | sed 's/\(JWT_SECRET=\)[^[:space:]]*/\1****/g' | sed 's/\(COOKIE_SECRET=\)[^[:space:]]*/\1****/g'
          
          # Copy to temp location for deployment
          mkdir -p /tmp
          cp backend/.env.${ENV_NAME} /tmp/backend.env
      
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add host key to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_HOST_KEY }}" >> ~/.ssh/known_hosts
      
      - name: Copy environment file to server
        run: |
          scp -o StrictHostKeyChecking=no /tmp/backend.env root@${{ secrets[format('BACKEND_{0}_IP', env.NODE_ENV == 'production' && 'PROD' || 'STAGING')] }}:/tmp/backend.env
      
      - name: Deploy to ${{ env.NODE_ENV }}
        run: |
          chmod +x ./scripts/deploy-backend.sh
          set -e  # Exit immediately if a command fails
          echo "Deploying to ${{ env.NODE_ENV }} environment using IP ${{ secrets[format('BACKEND_{0}_IP', env.NODE_ENV == 'production' && 'PROD' || 'STAGING')] }}"
          # Export the DB_PASSWORD so it's accessible to the SSH session
          export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
          # Pass DB_PASSWORD as an environment variable to the SSH session
          ./scripts/deploy-backend.sh ${{ env.NODE_ENV }} ${{ secrets[format('BACKEND_{0}_IP', env.NODE_ENV == 'production' && 'PROD' || 'STAGING')] }}
      
      - name: Verify deployment
        if: success()
        run: |
          echo "Backend successfully deployed to ${{ env.NODE_ENV }} environment!" 