name: Deploy to Staging

on:
  push:
    branches: [ staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.4.0 --activate

      - name: Debug Environment
        run: |
          echo "GitHub Actions runner user: $(whoami)"
          echo "SSH version: $(ssh -V 2>&1)"
          echo "OpenSSL version: $(openssl version)"
      
      - name: Debug SSH key format
        run: |
          # Display first line of key to check format (without exposing the actual key)
          echo "${{ secrets.STAGING_SSH_PRIVATE_KEY }}" | head -n 1 | echo "First line of key: $(cat)"
          # Check if key contains proper openssh header
          if echo "${{ secrets.STAGING_SSH_PRIVATE_KEY }}" | grep -q "BEGIN OPENSSH PRIVATE KEY"; then
            echo "Key has OpenSSH format header"
          elif echo "${{ secrets.STAGING_SSH_PRIVATE_KEY }}" | grep -q "BEGIN RSA PRIVATE KEY"; then
            echo "Key has RSA format header"
          else
            echo "Key does not have standard header"
          fi

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.STAGING_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ls -la ~/.ssh
          ssh-keygen -y -f ~/.ssh/id_ed25519 > ~/.ssh/id_ed25519.pub || echo "Failed to extract public key, but continuing"
          if [ -f ~/.ssh/id_ed25519.pub ]; then
            echo "Public key content (safe to display):"
            cat ~/.ssh/id_ed25519.pub
          fi
          
      - name: Verify Backend Connection
        env:
          BACKEND_HOST: ${{ secrets.STAGING_BACKEND_HOST }}
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
        run: |
          echo "Verifying connection to backend: $SSH_USER@$BACKEND_HOST"
          ssh-keyscan -H $BACKEND_HOST >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 $SSH_USER@$BACKEND_HOST "echo 'SSH connection successful'"

      - name: Deploy Backend
        env:
          BACKEND_HOST: ${{ secrets.STAGING_BACKEND_HOST }}
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
        run: |
          echo "Copying files to backend server..."
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519" --exclude node_modules --exclude .git ./backend/ $SSH_USER@$BACKEND_HOST:/home/root/app/
          
          echo "Running deployment script..."
          ssh -i ~/.ssh/id_ed25519 $SSH_USER@$BACKEND_HOST "cd /home/root/app && chmod +x scripts/deploy.sh && NODE_TLS_REJECT_UNAUTHORIZED=0 bash scripts/deploy.sh"
          
          echo "Checking SSL certificates..."
          ssh -i ~/.ssh/id_ed25519 $SSH_USER@$BACKEND_HOST 'certbot renew --non-interactive || true'
      
      - name: Setup Placeholder Key for Storefront
        run: |
          # Use a placeholder key regardless of backend status
          PLACEHOLDER_KEY="pk_staging_$(date +%s | md5sum | head -c 12)"
          echo "Using placeholder key for storefront: ${PLACEHOLDER_KEY:0:5}*****"
          echo "MEDUSA_PUBLISHABLE_KEY=${PLACEHOLDER_KEY}" >> $GITHUB_ENV
          echo "NOTE: You'll need to generate a proper publishable key from the admin dashboard after deployment"

      - name: Verify Storefront Connection
        env:
          STOREFRONT_HOST: ${{ secrets.STAGING_STOREFRONT_HOST }}
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
        run: |
          echo "Verifying connection to storefront: $SSH_USER@$STOREFRONT_HOST"
          echo "SSH_USER value: $SSH_USER"
          echo "STOREFRONT_HOST value: $STOREFRONT_HOST"
          
          # Make sure the key is in the known hosts
          ssh-keyscan -H $STOREFRONT_HOST >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
          
          # Check SSH key permissions again
          ls -la ~/.ssh
          
          # Try to connect with verbose debugging
          ssh -vvv -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 $SSH_USER@$STOREFRONT_HOST "echo 'SSH connection successful'"

      - name: Deploy Storefront
        env:
          STOREFRONT_HOST: ${{ secrets.STAGING_STOREFRONT_HOST }}
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          MEDUSA_PUBLISHABLE_KEY: ${{ env.MEDUSA_PUBLISHABLE_KEY }}
        run: |
          # Verify we have a publishable key before continuing
          if [ -z "$MEDUSA_PUBLISHABLE_KEY" ]; then
            echo "ERROR: No publishable key available. Cannot deploy storefront."
            exit 1
          fi
          
          echo "Copying files to storefront server..."
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519" --exclude node_modules --exclude .git ./storefront/ $SSH_USER@$STOREFRONT_HOST:/home/root/app/
          
          # Create/update .env with the publishable key
          echo "Setting up environment for deployment with publishable key..."
          ssh -i ~/.ssh/id_ed25519 $SSH_USER@$STOREFRONT_HOST "cd /home/root/app && cp .env.staging .env && sed -i '/NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=/d' .env && echo 'NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=${MEDUSA_PUBLISHABLE_KEY}' >> .env"
          
          echo "Running deployment script..."
          ssh -i ~/.ssh/id_ed25519 $SSH_USER@$STOREFRONT_HOST "cd /home/root/app && chmod +x scripts/deploy.sh && NODE_TLS_REJECT_UNAUTHORIZED=0 bash scripts/deploy.sh"
          
          echo "Checking SSL certificates..."
          ssh -i ~/.ssh/id_ed25519 $SSH_USER@$STOREFRONT_HOST 'certbot renew --non-interactive || true' 